server:
  servlet:
    context-path: /api/auth

logging:
  level:
    root: DEBUG

#security:
#  oauth2:
#    client:
#      client-id: postman
#      client-secret: postman
#      authorized-grant-types: authorization,password,refresh_token,password,client_credentials
#      scope: read,write
