logstash:
  server: logstash:50000
server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
  security:
    enabled: false
spring:
  application:
    name: service-registry
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false