logstash:
  server: logstash:50000
spring:
  application:
    name: gateway
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin:9411/
    sender:
      type: web

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY:http://localhost:8761/eureka}
