logstash:
  server: logstash:50000
server:
  port: 8080
aws:
  endpoint: http://localhost:4566

ribbon:
  eureka:
    enabled: false

spring:
  application:
    name: resource-processor
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin:9411/
    sender:
      type: web

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
  security:
    enabled: false
