logstash:
    server: logstash:50000
eureka:
    client:
        serviceUrl:
            defaultZone: ${SERVICE_REGISTRY:http://localhost:8761/eureka}
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        metrics:
            enabled: true
    security:
        enabled: false
spring:
    application:
        name: song
    datasource:
        driverClassName: org.postgresql.Driver
        password: password
        url: jdbc:postgresql://localhost:5432/postgres
        username: user
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create