openapi: 3.0.0
servers: []
info:
  description: Common models
  version: "1.0.0"
  title: Common models
paths:
  /cork:
    get:
      summary: cork to generate models
      responses:
        200:
          description: success
components:
  schemas:
    ErrorModel:
      type: object
      properties:
        message:
          type: string
          example: error
        code:
          type: integer
          format: int64
      required:
        - message
        - code