openapi: 3.0.0
servers: []
info:
  description: The API of the resource service
  version: '1.0'
  title: Resource service API
paths:
  /api/resources:
    delete:
      tags:
        - resource
      summary: delete resource
      operationId: deleteResource
      parameters:
        - in: query
          name: ids
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeletedResourcesView'

    post:
      summary: save resource
      operationId: saveResource
      tags:
        - resource
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            enum: [multipart/form-data]
        - in: header
          name: Resource-Type
          required: true
          schema:
            type: string
            enum: [audio/mpeg]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
                - file
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceIdView'
  /api/resources/{id}:
    get:
      tags:
        - resource
      summary: get resource
      operationId: getResource
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: success
          content:
            audio/mpeg:
              schema:
                type: string
                format: binary
components:
  schemas:
    DeletedResourcesView:
      type: object
      properties:
        ids:
          type: array
          items:
            type: integer
            format: int64
      required:
        - ids
    ResourceIdView:
      type: object
      properties:
        id:
          type: integer
          format: int64
      required:
        - id