openapi: 3.0.0
servers: []
info:
  description: The API of the song service
  version: '1.0'
  title: Song service API
paths:
  /api/songs/{songId}:
    get:
      operationId: getSongById
      tags:
        - song
      summary: get song by id
      parameters:
        - name: songId
          in: path
          description: song's id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongView'
  /api/songs:
    post:
      operationId: saveSong
      tags:
        - song
      summary: save song
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SongView'
        required: true
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongIdView'
    delete:
      operationId: deleteSongsByIds
      tags:
        - song
      summary: delete song
      parameters:
        - name: ids
          in: query
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteSongIds'
components:
  schemas:
    SongIdView:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
    SongView:
      type: object
      properties:
        name:
          type: string
          format: int64
          example: skibidi
        artist:
          type: string
          example: little big
        album:
          type: string
          example: xxx
        length:
          type: string
          example: 1000.02
        resourceId:
          type: integer
          format: int64
          example: 1
        year:
          type: string
          example: 2018
    DeleteSongIds:
      type: object
      properties:
        ids:
          type: array
          items:
            type: integer
            format: int64