openapi: 3.0.0
servers: []
info:
  version: '1.0'
  title: Storage service API
  description: The API of the storage service
paths:
  /api/storages:
    post:
      operationId: createStorage
      tags:
        - storage
      summary: create storage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StorageView'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StorageIdView'
    get:
      summary: get list of storages
      operationId: getStorageList
      tags:
        - storage
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StorageWithIdView'
    delete:
      summary: delete storages by their ids
      operationId: deleteStoragesByIds
      tags:
        - storage
      parameters:
        - name: ids
          in: query
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StorageIdView'
components:
  schemas:
    StorageIdView:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1123
    StorageWithIdView:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1123
        storageType:
          type: string
          example: PERMANENT
        bucket:
          type: string
          example: bucket_name
        path:
          type: string
          example: /files
    StorageView:
      type: object
      properties:
        storageType:
          type: string
          example: PERMANENT
        bucket:
          type: string
          example: bucket_name
        path:
          type: string
          example: /files