logstash:
  server: logstash:50000
eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY:http://localhost:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
  security:
    enabled: false
spring:
  application:
    name: storage
  datasource:
    driverClassName: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloack:8080/realms/epam
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: storage
            authorization-grant-type: authorization_code
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: http://keycloack:8080/realms/epam

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin:9411/
    sender:
      type: web
