logstash:
  server: logstash:50000
aws:
  endpoint: http://localhost:4566

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY:http://localhost:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
  security:
    enabled: false
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: resource
  datasource:
    driverClassName: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin:9411/
    sender:
      type: web
